/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:59:00 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.magneteng.restbyexamples.google.model.beans.*;

public interface GoogleDistanceMatrix {

  /**
   * Generated from URL GET http://maps.googleapis.com/maps/api/distancematrix/json?origins=435+Tasso+Street+Palo+Alto+CA&destinations=Embarcadero+Street+San+Francisco+CA&sensor=false&mode=driving&language=en&units=imperial
   * GET maps/api/distancematrix/json
   * @param origins  style:QUERY
   * @param destinations  style:QUERY
   * @param sensor  style:QUERY
   * @param mode  style:QUERY
   * @param language  style:QUERY
   * @param units  style:QUERY
   * @param listener
   * @return GoogleDistanceMatrixResult
   */
  Call<GoogleDistanceMatrixResult> getDistanceMatrix(
          String origins,
          String destinations,
          String sensor,
          String mode,
          String language,
          String units,
          StateChangedListener listener
  );


}
