/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:53:46 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.magneteng.restbyexamples.google.model.beans.*;

public class GoogleGeoCodeFactory extends ControllerFactory<GoogleGeoCode> {
  public GoogleGeoCodeFactory(MagnetMobileClient magnetClient) {
    super(GoogleGeoCode.class, GoogleGeoCodeSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller GoogleGeoCode
  public static class GoogleGeoCodeSchemaFactory extends AbstractControllerSchemaFactory {
    private static GoogleGeoCodeSchemaFactory __instance;

    public static synchronized GoogleGeoCodeSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new GoogleGeoCodeSchemaFactory();
      }

      return __instance;
    }

    private GoogleGeoCodeSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getGeoCode
      JMethod method1 = addMethod("getGeoCode",
        "maps/api/geocode/json",
        "GET",
        GeoCodeResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://maps.googleapis.com");
      method1.addParam("address",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("sensor",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
