/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:53:45 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.magneteng.restbyexamples.google.model.beans.*;

public interface GoogleGeoCode {

  /**
   * Generated from URL GET http://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&sensor=true
   * GET maps/api/geocode/json
   * @param address  style:QUERY
   * @param sensor  style:QUERY
   * @param listener
   * @return GeoCodeResult
   */
  Call<GeoCodeResult> getGeoCode(
     String address,
     String sensor,
     StateChangedListener listener
  );


}
