/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:59:00 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magnet.android.mms.controller.RequestSchema.JMeta;
import com.magnet.android.mms.controller.RequestSchema.JParam;

import java.util.Arrays;
import java.util.Collection;

import com.magneteng.restbyexamples.google.model.beans.*;

public class GoogleDistanceMatrixFactory extends ControllerFactory<GoogleDistanceMatrix> {
  public GoogleDistanceMatrixFactory(MagnetMobileClient magnetClient) {
    super(GoogleDistanceMatrix.class, GoogleDistanceMatrixSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller GoogleDistanceMatrix
  public static class GoogleDistanceMatrixSchemaFactory extends AbstractControllerSchemaFactory {
    private static GoogleDistanceMatrixSchemaFactory __instance;

    public static synchronized GoogleDistanceMatrixSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new GoogleDistanceMatrixSchemaFactory();
      }

      return __instance;
    }

    private GoogleDistanceMatrixSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getDistanceMatrix
      JMethod method1 = addMethod("getDistanceMatrix",
        "maps/api/distancematrix/json",
        "GET",
        GoogleDistanceMatrixResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://maps.googleapis.com");
      method1.addParam("origins",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("destinations",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("sensor",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("mode",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("language",
        "QUERY",
        String.class,
        null,
        "",
        true);
      method1.addParam("units",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
