/**
 * File generated by Magnet rest2mobile 1.0 - Sep 18, 2014 5:28:36 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.earthquake.api.controller;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;
import com.magneteng.earthquake.api.beans.*;

public interface EarthQuakeApi {

  /**
   * Generated from URL GET http://www.seismi.org/api/eqs/2011/03?min_magnitude=6
   * GET api/eqs/2011/03
   * @param min_magnitude  style:QUERY
   * @param listener
   * @return EventsResult
   */
  Call<EventsResult> getEvents(
      String min_magnitude,
      StateChangedListener listener
  );


}
