/**
 * File generated by Magnet rest2mobile 1.0 - Sep 18, 2014 5:28:36 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.earthquake.api.controller;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;
import com.magneteng.earthquake.api.beans.EventsResult;
import com.magneteng.earthquake.api.controller.EarthQuakeApi;

import java.util.Arrays;

public class EarthQuakeApiFactory extends ControllerFactory<EarthQuakeApi> {
  public EarthQuakeApiFactory(MagnetMobileClient magnetClient) {
    super(EarthQuakeApi.class, EarthQuakeApiSchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller EarthQuakeApi
  public static class EarthQuakeApiSchemaFactory extends AbstractControllerSchemaFactory {
    private static EarthQuakeApiSchemaFactory __instance;

    public static synchronized EarthQuakeApiSchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new EarthQuakeApiSchemaFactory();
      }

      return __instance;
    }

    private EarthQuakeApiSchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getEvents
      JMethod method1 = addMethod("getEvents",
        "api/eqs/2011/03",
        "GET",
        EventsResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("http://www.seismi.org");
      method1.addParam("min_magnitude",
        "QUERY",
        String.class,
        null,
        "",
        true);
    }

  }

}
