/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:53:45 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "long_name" : "1600",
  "short_name" : "1600",
  "types" : [ "street_number" ]
}

 */

public class Address_component {
  
  private String long_name;
  
  private String short_name;
  
  private List<java.lang.String> types;

  public String getLong_name() {
    return long_name;
  }
  public String getShort_name() {
    return short_name;
  }
  public List<java.lang.String> getTypes() {
    return types;
  }

  /**
  * Builder for Address_component
  **/
  public static class Address_componentBuilder {
    private Address_component toBuild = new Address_component();

    public Address_componentBuilder() {
    }

    public Address_component build() {
      return toBuild;
    }

    public Address_componentBuilder long_name(String value) {
      toBuild.long_name = value;
      return this;
    }
    public Address_componentBuilder short_name(String value) {
      toBuild.short_name = value;
      return this;
    }
    public Address_componentBuilder types(List<java.lang.String> value) {
      toBuild.types = value;
      return this;
    }
  }
}
