/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:59:00 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.model.beans;


/**
 * Generated from json example
{
  "text" : "34.4mi",
  "value" : 55389
}

 */

public class Distance {
  
  private String text;
  
  private Integer value;

  public String getText() {
    return text;
  }
  public Integer getValue() {
    return value;
  }

  /**
  * Builder for Distance
  **/
  public static class DistanceBuilder {
    private Distance toBuild = new Distance();

    public DistanceBuilder() {
    }

    public Distance build() {
      return toBuild;
    }

    public DistanceBuilder text(String value) {
      toBuild.text = value;
      return this;
    }
    public DistanceBuilder value(Integer value) {
      toBuild.value = value;
      return this;
    }
  }
}
