/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:53:45 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.model.beans;


/**
 * Generated from json example
{
  "location" : {
    "lat" : 37.4222953,
    "lng" : -122.0840671
  },
  "location_type" : "ROOFTOP",
  "viewport" : {
    "northeast" : {
      "lat" : 37.42364428029151,
      "lng" : -122.0827181197085
    },
    "southwest" : {
      "lat" : 37.42094631970851,
      "lng" : -122.0854160802915
    }
  }
}

 */

public class Geometry {
  
  private Location location;
  
  private String location_type;
  
  private Viewport viewport;

  public Location getLocation() {
    return location;
  }
  public String getLocation_type() {
    return location_type;
  }
  public Viewport getViewport() {
    return viewport;
  }

  /**
  * Builder for Geometry
  **/
  public static class GeometryBuilder {
    private Geometry toBuild = new Geometry();

    public GeometryBuilder() {
    }

    public Geometry build() {
      return toBuild;
    }

    public GeometryBuilder location(Location value) {
      toBuild.location = value;
      return this;
    }
    public GeometryBuilder location_type(String value) {
      toBuild.location_type = value;
      return this;
    }
    public GeometryBuilder viewport(Viewport value) {
      toBuild.viewport = value;
      return this;
    }
  }
}
