/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:59:00 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "destination_addresses" : [ "EmbarcaderoNorthStreet,SanFrancisco,CA,USA" ],
  "origin_addresses" : [ "435TassoStreet,PaloAlto,CA94301,USA" ],
  "rows" : [ {
    "elements" : [ {
      "distance" : {
        "text" : "34.4mi",
        "value" : 55389
      },
      "duration" : {
        "text" : "45mins",
        "value" : 2727
      },
      "status" : "OK"
    } ]
  } ],
  "status" : "OK"
}

 */

public class GoogleDistanceMatrixResult {
  
  private List<java.lang.String> destination_addresses;
  
  private List<java.lang.String> origin_addresses;
  
  private List<Row> rows;
  
  private String status;

  public List<java.lang.String> getDestination_addresses() {
    return destination_addresses;
  }
  public List<java.lang.String> getOrigin_addresses() {
    return origin_addresses;
  }
  public List<Row> getRows() {
    return rows;
  }
  public String getStatus() {
    return status;
  }

  /**
  * Builder for GoogleDistanceMatrixResult
  **/
  public static class GoogleDistanceMatrixResultBuilder {
    private GoogleDistanceMatrixResult toBuild = new GoogleDistanceMatrixResult();

    public GoogleDistanceMatrixResultBuilder() {
    }

    public GoogleDistanceMatrixResult build() {
      return toBuild;
    }

    public GoogleDistanceMatrixResultBuilder destination_addresses(List<java.lang.String> value) {
      toBuild.destination_addresses = value;
      return this;
    }
    public GoogleDistanceMatrixResultBuilder origin_addresses(List<java.lang.String> value) {
      toBuild.origin_addresses = value;
      return this;
    }
    public GoogleDistanceMatrixResultBuilder rows(List<Row> value) {
      toBuild.rows = value;
      return this;
    }
    public GoogleDistanceMatrixResultBuilder status(String value) {
      toBuild.status = value;
      return this;
    }
  }
}
