/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:53:45 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.model.beans;


/**
 * Generated from json example
{
  "lat" : 37.4222953,
  "lng" : -122.0840671
}

 */

public class Location {
  
  private Double lat;
  
  private Double lng;

  public Double getLat() {
    return lat;
  }
  public Double getLng() {
    return lng;
  }

  /**
  * Builder for Location
  **/
  public static class LocationBuilder {
    private Location toBuild = new Location();

    public LocationBuilder() {
    }

    public Location build() {
      return toBuild;
    }

    public LocationBuilder lat(Double value) {
      toBuild.lat = value;
      return this;
    }
    public LocationBuilder lng(Double value) {
      toBuild.lng = value;
      return this;
    }
  }
}
