/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:59:00 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.model.beans;

import java.util.List;

/**
 * Generated from json example
{
  "elements" : [ {
    "distance" : {
      "text" : "34.4mi",
      "value" : 55389
    },
    "duration" : {
      "text" : "45mins",
      "value" : 2727
    },
    "status" : "OK"
  } ]
}

 */

public class Row {
  
  private List<Element> elements;

  public List<Element> getElements() {
    return elements;
  }

  /**
  * Builder for Row
  **/
  public static class RowBuilder {
    private Row toBuild = new Row();

    public RowBuilder() {
    }

    public Row build() {
      return toBuild;
    }

    public RowBuilder elements(List<Element> value) {
      toBuild.elements = value;
      return this;
    }
  }
}
