/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:53:45 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.model.beans;


/**
 * Generated from json example
{
  "lat" : 37.42094631970851,
  "lng" : -122.0854160802915
}

 */

public class Southwest {
  
  private Double lat;
  
  private Double lng;

  public Double getLat() {
    return lat;
  }
  public Double getLng() {
    return lng;
  }

  /**
  * Builder for Southwest
  **/
  public static class SouthwestBuilder {
    private Southwest toBuild = new Southwest();

    public SouthwestBuilder() {
    }

    public Southwest build() {
      return toBuild;
    }

    public SouthwestBuilder lat(Double value) {
      toBuild.lat = value;
      return this;
    }
    public SouthwestBuilder lng(Double value) {
      toBuild.lng = value;
      return this;
    }
  }
}
