/**
 * File generated by Magnet rest2mobile 1.0 - Sep 23, 2014 1:53:45 PM
 * @see {@link http://developer.magnet.com}
 */

package com.magneteng.restbyexamples.google.model.beans;


/**
 * Generated from json example
{
  "northeast" : {
    "lat" : 37.42364428029151,
    "lng" : -122.0827181197085
  },
  "southwest" : {
    "lat" : 37.42094631970851,
    "lng" : -122.0854160802915
  }
}

 */

public class Viewport {
  
  private Northeast northeast;
  
  private Southwest southwest;

  public Northeast getNortheast() {
    return northeast;
  }
  public Southwest getSouthwest() {
    return southwest;
  }

  /**
  * Builder for Viewport
  **/
  public static class ViewportBuilder {
    private Viewport toBuild = new Viewport();

    public ViewportBuilder() {
    }

    public Viewport build() {
      return toBuild;
    }

    public ViewportBuilder northeast(Northeast value) {
      toBuild.northeast = value;
      return this;
    }
    public ViewportBuilder southwest(Southwest value) {
      toBuild.southwest = value;
      return this;
    }
  }
}
