/**
 * File generated by Magnet rest2mobile 1.0 - Sep 18, 2014 5:28:36 PM
 * @see {@link http://developer.magnet.com}
 */


/** Generated from json example
{
  "count" : "62",
  "earthquakes" : [ {
    "src" : "us",
    "eqid" : "c0002fj4",
    "timedate" : "2011-03-3107:15:30",
    "lat" : "38.9536",
    "lon" : "142.0174",
    "magnitude" : "6.2",
    "depth" : "39.6",
    "region" : "neartheeastcoastofHonshu,Japan"
  }, {
    "src" : "us",
    "eqid" : "c0002fen",
    "timedate" : "2011-03-3100:11:59",
    "lat" : "-16.5663",
    "lon" : "-177.4925",
    "magnitude" : "6.4",
    "depth" : "23.7",
    "region" : "FijiRegion"
   ...

*/

package com.magneteng.earthquake.api.beans;

import java.util.List;

public class EventsResult {
  
  private String count;
  
  private List<Earthquake> earthquakes;

  public String getCount() {
    return count;
  }
  public List<Earthquake> getEarthquakes() {
    return earthquakes;
  }

  /**
  * Builder for EventsResult
  **/
  public static class EventsResultBuilder {
    private EventsResult toBuild = new EventsResult();

    public EventsResultBuilder() {
    }

    public EventsResult build() {
      return toBuild;
    }

    public EventsResultBuilder count(String value) {
      toBuild.count = value;
      return this;
    }
    public EventsResultBuilder earthquakes(List<Earthquake> value) {
      toBuild.earthquakes = value;
      return this;
    }
  }
}
