/**
 * File generated by Magnet rest2mobile 1.0 - Sep 28, 2014 10:59:48 PM
 * @see {@link http://developer.magnet.com}
 */

package com.twitter.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;

import com.twitter.model.beans.*;

public interface TwitterPrivacy {

  /**
   * Generated from URL GET https://api.twitter.com/1.1/help/privacy.json
   * GET 1.1/help/privacy.json
   * @param listener
   * @return PrivacyResult
   */
  Call<PrivacyResult> getPrivacy(StateChangedListener listener);
}
