/**
 * File generated by Magnet rest2mobile 1.0 - Sep 28, 2014 10:59:48 PM
 * @see {@link http://developer.magnet.com}
 */

package com.twitter.controller.api;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.controller.ControllerFactory;
import com.magnet.android.mms.controller.AbstractControllerSchemaFactory;
import com.magnet.android.mms.controller.RequestSchema;
import com.magnet.android.mms.controller.RequestSchema.JMethod;

import java.util.Arrays;

import com.twitter.model.beans.*;

public class TwitterPrivacyFactory extends ControllerFactory<TwitterPrivacy> {
  public TwitterPrivacyFactory(MagnetMobileClient magnetClient) {
    super(TwitterPrivacy.class, TwitterPrivacySchemaFactory.getInstance().getSchema(), magnetClient);
  }

  // Schema factory for controller TwitterPrivacy
  public static class TwitterPrivacySchemaFactory extends AbstractControllerSchemaFactory {
    private static TwitterPrivacySchemaFactory __instance;

    public static synchronized TwitterPrivacySchemaFactory getInstance() {
      if(null == __instance) {
        __instance = new TwitterPrivacySchemaFactory();
      }

      return __instance;
    }

    private TwitterPrivacySchemaFactory() {}

    protected synchronized void initSchemaMaps() {
      if(null != schema) {
        return;
      }

      schema = new RequestSchema();
      schema.setRootPath("");

      //controller schema for controller method getPrivacy
      JMethod method1 = addMethod("getPrivacy",
        "1.1/help/privacy.json",
        "GET",
        PrivacyResult.class,
        null,
        null,
        Arrays.asList("application/json"));
      method1.setBaseUrl("https://api.twitter.com");
    }

  }

}
